### ISSUE TITLE
Sobre mock-up DevsLatam y cómo participar

### ISSUE THREAD

**Issue by jaimecuellar** [Trycatch-tv/devs-latam-frontend#3]
Hola! Se ha mencionado mucho en las transmisiones Try Catch que nos pasemos por acá.
No veo el mock-up de la página, sólo Discord. Entendí que se iba a dejar acá también.
Si me lo he perdido y ya está, soy algo nuevo en esto, así que agradezco algunas indicaciones sobre verlo y sobre cómo participar.
Feliz día.

**Comment by judlup** [comment]
Hola @jaimecuellar gracias, no recordaba que no había incluído el mockup en el repo, ya fue incluído, gracias por estar por aquí

**Comment by jaimecuellar** [comment]
Súper!
